project_id = "end-to-end-gcp"
region     = "europe-west1"
zone       = "europe-west1-b"
subnetwork = "projects/end-to-end-gcp/regions/europe-west1/subnetworks/default"
service_account_email = "288578193600-compute@developer.gserviceaccount.com"
